OKAPI-1187: Illegal base64 character 5f on token with umlaut
Calling okapi-common’s new OkapiToken("x.eyJzdWIiOiJmb2_DpCJ9.x") throws this exception:

```
java.lang.IllegalArgumentException: Illegal base64 character 5f
        at java.base/java.util.Base64$Decoder.decode0(Base64.java:848)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:566)
        at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
        at org.folio.okapi.common.OkapiToken.init(OkapiToken.java:41)
        at org.folio.okapi.common.OkapiToken.<init>(OkapiToken.java:24)
```

The encoded payload should be properly decoded to `{"sub":"fooä"}`

Cause:

```
new String(Base64.getDecoder().decode(encodedJson));
```

Correct code:

```
new String(Base64.getUrlDecoder().decode(encodedJson), UTF_8);
```