No need to check for tenant 'pg'
As enabling a module will fail anyway with something like:
CREATE ROLE pg_mod_users PASSWORD 'pg' NOSUPERUSER NOCREATEDB INHERIT LOGIN;
ERROR: role name "pg_mod_users" is reserved (42939)